### ISSUE TITLE
openwrt中的openclash 如何使用

### ISSUE THREAD

**Issue by wonathan** [Hackl0us/GeoIP2-CN#1]
如题

**Comment by nb5p** [comment]
1. 替换`/etc/openclash/Country.mmdb`文件
2. 重启Clash

**Comment by goukey** [comment]
直接替换geoip的更新地址，一次替换一劳永逸：
1.打开/usr/share/openclash/openclash_ipdb.sh。
2.替换其中Country.mmdb文件链接，共两处，可设主备两个地址。
3.Enjoy

**Comment by wazituzi** [comment]
openclash最新版已经支持自己切换geoip源了

**Comment by goukey** [comment]
openclash从0.40之后的版本就是bug无数

**Comment by Hackl0us** [comment]
在 OpenClash 最新的发布版本 0.41.07 版本中已经添加了自定义 GeoIP 和 IP 地址段的功能，感谢 @vernesong 的支持。
