### ISSUE TITLE
建议修改 README 中 clash 的描述

### ISSUE THREAD

**Issue by Azureki** [Hackl0us/GeoIP2-CN#10]
[README](https://github.com/Hackl0us/GeoIP2-CN#clash)中说
> Clash 及其衍生工具（如 Clash X, Clash for Windows, **Clash for Android**, OpenClash 等）的用户直接通过上面链接下载 Country.mmdb 并替换掉 Clash 配置文件夹下的同名文件即可。

事实上，**clash for android** 并不支持自定义，参考：
https://github.com/Kr328/ClashForAndroid/issues/749
https://github.com/Kr328/ClashForAndroid/issues/411#issuecomment-640780469

**Comment by Hackl0us** [comment]
感谢，已经相关描述并补充了其他代理工具的详细配置方式。 参见 master@a97f6e8
