### ISSUE TITLE
这个网站好像不能正常识别

### ISSUE THREAD

**Issue by xieft** [Hackl0us/GeoIP2-CN#13]
https://mixin.one/messenger

**Comment by Hackl0us** [comment]
不能识别的意思是？

`mixin.one` 的 DNS 解析的结果是 `35.201.68.20`，是 Google 广播的 IP 地址，属于美国。这个地址库当然识别不出来，没有什么问题啊。

**Comment by xieft** [comment]
但是不知道为什么会被识别为直连。。。
