### ISSUE TITLE
wps错误

### ISSUE THREAD

**Issue by Arrogance-H** [Hackl0us/GeoIP2-CN#14]
wps连接会被识别为others

**Comment by Hackl0us** [comment]
能否给我相关域名？谢谢

**Comment by Arrogance-H** [comment]
![969FF9B5-3EFD-4FFB-A2CE-82EC49DC1525](https://user-images.githubusercontent.com/68095403/102332503-22cf8800-3fc7-11eb-811d-4fdadd80b616.png)

**Comment by Hackl0us** [comment]
您好，我这边测试没有任何问题。

`deviceapi.wps.cn` 的 IP 地址是 `120.131.2.130`，我调用同样的数据库判定后是属于 CN 的。
`

<img width="608" alt="image" src="https://user-images.githubusercontent.com/10215166/102368749-29292880-3ff6-11eb-8d4b-881d2ca3ec2d.png">
