### ISSUE TITLE
Clash DNS fallback-filter 失效

### ISSUE THREAD

**Issue by qcts33** [Hackl0us/GeoIP2-CN#16]
使用clash作为抗污染DNS服务器时可以基于geoip对查询结果进行过滤，只有IP地址属于CN才返回默认结果，否则返回fallback结果。
但使用本项目的数据库之后fallback会失效，不管查询什么内容都只返回可能被污染的默认结果。
个人猜测是因为clash对IP查询失败之后就继续采用默认结果造成的。不知道能不能增加一个兜底IP结果，将非CN的IP结果返回一个不存在的国家码，从而触发clash的fallback

**Comment by wzy461143268** [comment]
https://github.com/alecthw/mmdb_china_ip_list
只替换CN的geoip库
