### ISSUE TITLE
目前Surge tf已支持自动更新geoip数据库

### ISSUE THREAD

**Issue by mangoclover** [Hackl0us/GeoIP2-CN#17]
如题

**Comment by luzhaohui** [comment]
正式版还不支持，要怎么搞？求教

**Comment by mangoclover** [comment]
> 正式版还不支持，要怎么搞？求教

两个办法，其一是等待作者更新正式版功能，其二是通过ruleset功能实现，但是会影响体验。

**Comment by luzhaohui** [comment]
> > 正式版还不支持，要怎么搞？求教
> 
> 两个办法，其一是等待作者更新正式版功能，其二是通过ruleset功能（须禁用Geoip规则）实现，list地址https://raw.githubusercontent.com/mangoclover/GeoIP2-CN/release/Surge-Ruleset.list

谢谢
