### ISSUE TITLE
49万条IP在QuantumlutX里用会不会卡死？

### ISSUE THREAD

**Issue by MisterGlasses** [Hackl0us/GeoIP2-CN#2]
ipip.net包含6010条 纯真包含4730条 怎么一合并就成了490000条了？
如果直接用在QuantumlutX里，手机能撑得住吗？

**Comment by Hackl0us** [comment]
我不知道您在哪个地方看到的纯真只有 4730 条？建议你看一下代码里使用的资源。

Quantumult X 可以直接使用项目提供的 GeoIP 2 数据库，详情配置方式请看项目主页。

**Comment by MisterGlasses** [comment]
> 我不知道您在哪个地方看到的纯真只有 4730 条？建议你看一下代码里使用的资源。
> 
> Quantumult X 可以直接使用项目提供的 GeoIP 2 数据库，详情配置方式请看项目主页。

我不太懂这个 看了下行数😂
![3DD1990C-9268-4271-91A0-FDD0C330B0C0](https://user-images.githubusercontent.com/27768847/101985434-f2d06e00-3cc2-11eb-9101-2e237a72f132.jpeg)

**Comment by Paris0-0** [comment]
这个ipcidr是要转换成二进制算的，每个数字8位一共32位，/n就是前n位不变后面(32-n)位可变共2^(32-n)个ip数
