### ISSUE TITLE
第一行是空行会导致ShadowSocksR Plus+ 无法使用 去掉就可以使用了 

### ISSUE THREAD

**Issue by h605290713** [Hackl0us/GeoIP2-CN#29]
第一行是空行会导致ShadowSocksR Plus+ 无法使用 去掉就可以使用了

**Comment by jqyisbest** [comment]
挺坑的这一点。直接导致SSRP无法将其设置为自动更新。

**Comment by devioa** [comment]
可以用`sed`命令删除首行，我以Hello World(SSRP的魔改版，路径和代码应该差不多)为例给你操作演示一下：
打开`/usr/share/vssr/update.lua`
定位到`log('正在更新【国内IP段】数据库')`
下面`refresh_cmd`在后面加上：`sed -i '/^$/d' /tmp/china_ssr.txt`
![1](https://user-images.githubusercontent.com/38558065/203467375-9250593c-ea65-407f-ade3-45eee719497d.png)
保存后在ssh里手动运行一下这个lua脚本：
`cd /usr/share/vssr && chmod +x update.lua && ./update.lua`
![2](https://user-images.githubusercontent.com/38558065/203467626-99d4caf5-2101-4e5a-92fa-4d997c226de5.png)
然后你再打开`/etc/vssr/china_ssr.txt`看首行就没有空格了
最后ssh重启一下梯子插件：`/etc/init.d/vssr restart`
最后就可以正常使用了

**Comment by devioa** [comment]
可以用`sed`命令删除首行，我以Hello World(SSRP的魔改版，路径和代码应该差不多)为例给你操作演示一下：
打开`/usr/share/vssr/update.lua`
定位到`log('正在更新【国内IP段】数据库')`
下面`refresh_cmd`在后面加上：`sed -i '/^$/d' /tmp/china_ssr.txt`
![1](https://user-images.githubusercontent.com/38558065/203467375-9250593c-ea65-407f-ade3-45eee719497d.png)
保存后在ssh里手动运行一下这个lua脚本：
`cd /usr/share/vssr && chmod +x update.lua && ./update.lua`
![2](https://user-images.githubusercontent.com/38558065/203467626-99d4caf5-2101-4e5a-92fa-4d997c226de5.png)
然后你再打开`/etc/vssr/china_ssr.txt`检查首行就没有空格了
最后ssh重启一下梯子插件：`/etc/init.d/vssr restart`，就可以正常使用了

**Comment by devioa** [comment]
可以用`sed`命令删除首行，我以Hello World(SSRP的魔改版，路径和代码应该差不多)为例给你操作演示一下：
打开`/usr/share/vssr/update.lua`
定位到`log('正在更新【国内IP段】数据库')`
下面`refresh_cmd`在后面加上：`sed -i '/^$/d' /tmp/china_ssr.txt`
![1](https://user-images.githubusercontent.com/38558065/203467375-9250593c-ea65-407f-ade3-45eee719497d.png)
保存后在ssh里手动运行一下这个lua脚本：
`cd /usr/share/vssr && chmod +x update.lua && ./update.lua`
![2](https://user-images.githubusercontent.com/38558065/203467626-99d4caf5-2101-4e5a-92fa-4d997c226de5.png)
然后你再打开`/etc/vssr/china_ssr.txt`检查首行就没有空行了
最后ssh重启一下梯子插件：`/etc/init.d/vssr restart`，就可以正常使用了
