### ISSUE TITLE
Quantumult X最新商店版，已经支持外挂的GeoIP

### ISSUE THREAD

**Issue by DockerCS** [Hackl0us/GeoIP2-CN#30]
点击Quantumult X的右下角风车图标，滑到底部—其他设置，继续滑到底部，GeoLite2有一个来源设置，可以填入您的GeoIP2-CN链接

**Comment by Hackl0us** [comment]
Thanks for your input, I've already add Quantumult X config tutorial on Wiki page 
https://github.com/Hackl0us/GeoIP2-CN/wiki/Quantumult-X
